name             'thoroughcare'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures thoroughcare'
long_description 'Installs/Configures thoroughcare'
version          '0.1.0'
depends          'apt'
depends          'postgresql', '~> 3.4.14'
